import React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text } from 'react-native';
import { router } from 'expo-router';
import { AppCard, Field, PrimaryButton, SecurityBadge } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { colors, spacing } from '@/theme';

export default function AuthScreen() { const { signIn, signUp, sendPasswordReset, error, configured } = useAuth(); const [mode, setMode] = React.useState<'signin'|'signup'|'reset'>('signin'); const [email, setEmail] = React.useState(''); const [password, setPassword] = React.useState(''); const [name, setName] = React.useState(''); const submit = async () => { if (mode === 'reset') { await sendPasswordReset(email); Alert.alert('Check your inbox', 'If that account is registered, a password reset link will arrive shortly.'); return; } const ok = mode === 'signin' ? await signIn(email, password) : await signUp(email, password, name); if (ok) { Alert.alert(mode === 'signin' ? 'Signed in' : 'Check your inbox', mode === 'signin' ? 'Your secure session is ready.' : 'If the address is eligible, verify your email to finish setup.'); if (mode === 'signin') router.back(); } };
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>Cancel</Text></Pressable><Text style={styles.eyebrow}>SECURE ACCESS</Text><Text style={styles.title}>Your financial workspace</Text><Text style={styles.sub}>Supabase Auth · verified email · encrypted mobile session</Text><SecurityBadge /><AppCard style={styles.card}>{mode === 'signup' ? <Field label="Full name" value={name} onChangeText={setName} placeholder="Ahmad Khan" /> : null}<Field label="Email" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="you@company.com" /><Field label="Password" value={password} onChangeText={setPassword} secureTextEntry placeholder={mode === 'reset' ? 'Not needed for reset' : 'At least 10 characters'} />{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton label={mode === 'signin' ? 'Sign in securely' : mode === 'signup' ? 'Create account' : 'Send reset link'} onPress={submit} /><Pressable onPress={() => setMode(mode === 'signin' ? 'signup' : 'signin')}><Text style={styles.switch}>{mode === 'signin' ? 'New here? Create an account' : 'Already have an account? Sign in'}</Text></Pressable>{mode === 'signin' ? <Pressable onPress={() => setMode('reset')}><Text style={styles.reset}>Forgot password?</Text></Pressable> : null}</AppCard>{!configured ? <Text style={styles.config}>Supabase is not configured in this build. Add the public project URL and anon key to `.env` before staging.</Text> : null}</ScrollView>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingTop: 58, paddingBottom: 50 }, back: { color: colors.orangeDark, fontWeight: '800', marginBottom: 34 }, eyebrow: { color: colors.textMuted, fontSize: 10, fontWeight: '900', letterSpacing: 1.4 }, title: { color: colors.ink, fontSize: 30, fontWeight: '900', marginTop: 10 }, sub: { color: colors.muted, marginTop: 6, lineHeight: 20 }, card: { marginTop: 24 }, error: { color: colors.danger, marginBottom: 14, lineHeight: 18 }, switch: { color: colors.orangeDark, fontWeight: '800', textAlign: 'center', marginTop: 18 }, reset: { color: colors.muted, textAlign: 'center', marginTop: 16 }, config: { color: colors.textMuted, textAlign: 'center', fontSize: 11, lineHeight: 17, marginTop: 22 } });
