import React from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { AppCard, Field, PrimaryButton, StatusPill } from '@/components/ui';
import { useApp } from '@/context/AppContext';
import { colors, money, spacing } from '@/theme';
import type { Invoice, Transaction } from '@/types';

export default function AddScreen() {
  const params = useLocalSearchParams<{ mode?: string }>();
  const initial = params.mode === 'income' || params.mode === 'expense' ? params.mode : 'expense';
  const [mode, setMode] = React.useState(initial);
  const [amount, setAmount] = React.useState('');
  const [merchant, setMerchant] = React.useState('');
  const [category, setCategory] = React.useState('');
  const [client, setClient] = React.useState('');
  const [project, setProject] = React.useState('');
  const [notes, setNotes] = React.useState('');
  const [receipt, setReceipt] = React.useState(params.mode === 'receipt');
  const [step, setStep] = React.useState<'form'|'confirm'>('form');
  const { addTransaction, addInvoice, settings } = useApp();
  const isInvoice = params.mode === 'invoice';
  const submit = () => { const value = Number(amount.replace(/[^0-9.]/g, '')); if (!value || !merchant.trim()) { Alert.alert('A little more detail', isInvoice ? 'Add a client and amount to continue.' : 'Add a name and amount to continue.'); return; } setStep('confirm'); };
  const save = () => { const value = Number(amount.replace(/[^0-9.]/g, '')); if (isInvoice) { const invoice: Invoice = { id: `INV-${1043 + Math.floor(Math.random() * 20)}`, client: merchant || client || 'New client', project: project || 'New project', amount: value, balanceDue: value, issueDate: new Date().toISOString().slice(0,10), dueDate: '2026-10-15', status: 'sent' }; addInvoice(invoice); Alert.alert('Invoice ready', 'Your new invoice is saved locally and ready to send.', [{ text: 'Done', onPress: () => router.back() }]); } else { const tx: Transaction = { id: `tx-${Date.now()}`, type: mode as 'income'|'expense', merchant, amount: value, date: new Date().toISOString().slice(0,10), category: category || (mode === 'income' ? 'Client payment' : 'Other'), client: client || undefined, project: project || undefined, paymentMethod: 'Bank', status: receipt ? 'Needs review' : 'Completed', notes }; addTransaction(tx); Alert.alert('Saved', receipt ? 'Receipt added to your review queue.' : `${mode === 'income' ? 'Income' : 'Expense'} saved to your workspace.`, [{ text: 'Done', onPress: () => router.back() }]); } };
  if (step === 'confirm') return <View style={styles.screen}><View style={styles.modalHeader}><Pressable onPress={() => setStep('form')}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.headerTitle}>Review before saving</Text><View style={{ width: 50 }} /></View><ScrollView contentContainerStyle={styles.content}><AppCard tone="lavender" style={styles.confirm}><Text style={styles.confirmKicker}>ONE LAST LOOK</Text><Text style={styles.confirmTitle}>{isInvoice ? 'Create this invoice?' : `Save this ${mode}?`}</Text><Text style={styles.confirmAmount}>{money(Number(amount), settings.currency)}</Text><Text style={styles.confirmName}>{merchant || client}</Text><Text style={styles.confirmMeta}>{category || 'Client payment'} · {project || 'Northstar Studio'}</Text><View style={styles.confirmLine}><StatusPill label={receipt ? 'Needs review' : 'Ready to save'} kind={receipt ? 'warning' : 'positive'} /></View></AppCard><PrimaryButton label={isInvoice ? 'Create invoice' : 'Save to LedgerFlow'} onPress={save} /></ScrollView></View>;
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.modalHeader}><Pressable onPress={() => router.back()}><Text style={styles.back}>Cancel</Text></Pressable><Text style={styles.headerTitle}>{isInvoice ? 'New invoice' : receipt ? 'Scan receipt' : mode === 'income' ? 'Add income' : 'Add expense'}</Text><View style={{ width: 50 }} /></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.intro}>{isInvoice ? 'Send a clear, friendly request for payment.' : receipt ? 'Capture the receipt, then review what LedgerFlow found.' : 'Record it now. Your future self will thank you.'}</Text>{!isInvoice && !receipt ? <View style={styles.segment}><Pressable onPress={() => setMode('income')} style={[styles.segmentItem, mode === 'income' && styles.segmentActive]}><Text style={[styles.segmentText, mode === 'income' && styles.segmentTextActive]}>Money in</Text></Pressable><Pressable onPress={() => setMode('expense')} style={[styles.segmentItem, mode === 'expense' && styles.segmentActive]}><Text style={[styles.segmentText, mode === 'expense' && styles.segmentTextActive]}>Money out</Text></Pressable></View> : null}{receipt ? <AppCard tone="yellow" style={styles.scanCard}><Text style={styles.scanIcon}>⌁</Text><Text style={styles.scanTitle}>Receipt captured</Text><Text style={styles.scanBody}>Mock scan complete · we found a likely match.</Text><StatusPill label="Review inferred details" kind="warning" /></AppCard> : null}<Field label={isInvoice ? 'Client name' : 'Merchant or client'} value={merchant} onChangeText={setMerchant} placeholder={isInvoice ? 'e.g. Acme Studio' : 'e.g. Figma or Acme Studio'} /><Field label="Amount" value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="0" /><Field label={isInvoice ? 'Project / line item' : 'Category'} value={isInvoice ? project : category} onChangeText={isInvoice ? setProject : setCategory} placeholder={isInvoice ? 'e.g. Brand refresh' : 'e.g. Software & Subscriptions'} /><Field label={isInvoice ? 'Notes for client' : 'Client / project (optional)'} value={isInvoice ? notes : client} onChangeText={isInvoice ? setNotes : setClient} placeholder={isInvoice ? 'Thank you for your partnership' : 'e.g. Northstar retainer'} /><PrimaryButton label={isInvoice ? 'Review invoice' : receipt ? 'Review extracted details' : 'Review & save'} onPress={submit} /></ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, modalHeader: { paddingTop: 58, paddingHorizontal: spacing.lg, paddingBottom: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.background }, back: { color: colors.orangeDark, fontWeight: '800', width: 52 }, headerTitle: { color: colors.ink, fontWeight: '900', fontSize: 16 }, content: { padding: spacing.lg, paddingBottom: 50 }, intro: { color: colors.muted, lineHeight: 20, marginBottom: 18 }, segment: { flexDirection: 'row', backgroundColor: colors.border, borderRadius: 14, padding: 3, marginBottom: 20 }, segmentItem: { flex: 1, paddingVertical: 12, alignItems: 'center', borderRadius: 11 }, segmentActive: { backgroundColor: colors.surface }, segmentText: { color: colors.muted, fontWeight: '800' }, segmentTextActive: { color: colors.ink }, scanCard: { alignItems: 'center', marginBottom: 20 }, scanIcon: { fontSize: 42, color: colors.orangeDark }, scanTitle: { color: colors.ink, fontWeight: '900', fontSize: 18, marginTop: 6 }, scanBody: { color: colors.muted, marginVertical: 8 }, confirm: { alignItems: 'center', marginBottom: 20 }, confirmKicker: { color: colors.orangeDark, fontSize: 11, fontWeight: '900', letterSpacing: 1 }, confirmTitle: { color: colors.ink, fontSize: 22, fontWeight: '900', marginTop: 12 }, confirmAmount: { color: colors.orangeDark, fontSize: 36, fontWeight: '900', marginTop: 20 }, confirmName: { color: colors.ink, fontSize: 16, fontWeight: '800', marginTop: 8 }, confirmMeta: { color: colors.muted, marginTop: 5 }, confirmLine: { marginTop: 18 }, });
