import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppCard, ScreenHeader, SecurityBadge, StatusPill } from '@/components/ui';
import { useApp } from '@/context/AppContext';
import { colors, money, spacing } from '@/theme';

const prompts = ['How is my business doing this month?', 'Who should I follow up with?', 'Where am I spending too much?', 'Can I afford to hire a designer?'];
export default function AssistantScreen() {
  const { transactions, invoices, settings } = useApp(); const [answer, setAnswer] = React.useState('');
  const respond = (prompt: string) => { if (prompt.startsWith('Who')) setAnswer('Start with PixelCraft. Their invoice is overdue and there is PKR 95,000 ready to collect. A kind follow-up today is the highest-impact action.'); else if (prompt.startsWith('Where')) setAnswer('Software spending is the clearest opportunity. It is up 22% this month, led by Figma and collaboration tools. Review seats before adding anything new.'); else if (prompt.startsWith('Can')) setAnswer('Based on this month’s cash position, a cautious hire looks possible, but keep a three-month buffer. This is decision support, not financial advice.'); else setAnswer(`You brought in ${money(transactions.filter((t) => t.type === 'income').reduce((s, t) => s + t.amount, 0), settings.currency)} and have ${invoices.filter((i) => i.balanceDue > 0).length} open invoices. Your business is moving in a healthy direction; collections are the next lever.`); };
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><ScreenHeader eyebrow="JEV AI" title="Your finance copilot" subtitle="Decision support grounded in your LedgerFlow workspace." action={<Text style={styles.spark}>✦</Text>} /><SecurityBadge /><AppCard tone="lavender" style={styles.disclaimer}><Text style={styles.disclaimerTitle}>Always review before acting</Text><Text style={styles.disclaimerBody}>Jev AI provides decision support, not financial, tax, or legal advice.</Text></AppCard><Text style={styles.promptLabel}>Try asking</Text>{prompts.map((prompt) => <Pressable key={prompt} onPress={() => respond(prompt)} style={({ pressed }) => [styles.prompt, pressed && { opacity: .7 }]}><Text style={styles.promptText}>{prompt}</Text><Text style={styles.arrow}>↗</Text></Pressable>)}{answer ? <AppCard tone="blue" style={styles.answer}><View style={styles.answerTop}><Text style={styles.answerKicker}>JEV AI RESPONSE</Text><StatusPill label="Evidence attached" kind="positive" /></View><Text style={styles.answerText}>{answer}</Text><View style={styles.evidence}><Text style={styles.evidenceTitle}>Evidence from your workspace</Text><Text style={styles.evidenceBody}>• 6 transactions · 4 invoices · local demo dataset</Text><Text style={styles.evidenceBody}>• No bank connection or external financial data used</Text></View></AppCard> : <AppCard style={styles.empty}><Text style={styles.emptyIcon}>✦</Text><Text style={styles.emptyTitle}>Ask a calm question</Text><Text style={styles.emptyBody}>Jev will show the numbers behind every answer.</Text></AppCard>}</ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingTop: 58, paddingBottom: 50 }, spark: { color: colors.purple, fontSize: 28 }, disclaimer: { marginTop: 18 }, disclaimerTitle: { color: colors.ink, fontWeight: '900', fontSize: 16 }, disclaimerBody: { color: colors.muted, marginTop: 6, lineHeight: 19 }, promptLabel: { color: colors.muted, fontWeight: '800', marginTop: 26, marginBottom: 10 }, prompt: { backgroundColor: colors.surface, borderRadius: 16, borderWidth: 1, borderColor: colors.border, padding: 16, marginBottom: 8, flexDirection: 'row', justifyContent: 'space-between' }, promptText: { color: colors.ink, fontWeight: '700', flex: 1 }, arrow: { color: colors.orangeDark, fontSize: 18 }, answer: { marginTop: 18 }, answerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, answerKicker: { color: colors.orangeDark, fontSize: 10, fontWeight: '900', letterSpacing: 1 }, answerText: { color: colors.ink, fontSize: 16, lineHeight: 24, fontWeight: '700', marginTop: 14 }, evidence: { marginTop: 18, paddingTop: 14, borderTopWidth: 1, borderTopColor: colors.border }, evidenceTitle: { color: colors.muted, fontWeight: '800', fontSize: 12 }, evidenceBody: { color: colors.textMuted, fontSize: 11, marginTop: 6 }, empty: { marginTop: 18, alignItems: 'center', paddingVertical: 30 }, emptyIcon: { color: colors.purple, fontSize: 34 }, emptyTitle: { color: colors.ink, fontSize: 18, fontWeight: '900', marginTop: 10 }, emptyBody: { color: colors.muted, marginTop: 6 } });
