import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { AppCard, MetricCard, MoneyText, ScreenHeader, SectionHeader, SecurityBadge } from '@/components/ui';
import { useApp } from '@/context/AppContext';
import { colors, compactMoney, money, spacing } from '@/theme';

export default function CommandCenter() {
  const { transactions, invoices, settings } = useApp();
  const revenue = transactions.filter((t) => t.type === 'income').reduce((s, t) => s + t.amount, 0);
  const expenses = transactions.filter((t) => t.type === 'expense').reduce((s, t) => s + t.amount, 0);
  const receivables = invoices.reduce((s, i) => s + i.balanceDue, 0);
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><ScreenHeader eyebrow="LEDGERFLOW EXECUTIVE" title="Command center" subtitle="A five-second read on the health of Northstar Studio." /><SecurityBadge /><View style={styles.heroRow}><MetricCard label="Net position" value={compactMoney(revenue - expenses, settings.currency)} detail="Revenue less expenses" tone="blue" /><MetricCard label="Cash position" value={compactMoney(642500 + revenue - expenses, settings.currency)} detail="Available today" tone="mint" /></View><SectionHeader title="Performance" action="September" /><AppCard tone="lavender"><Text style={styles.cardKicker}>PROFIT & LOSS</Text><Text style={styles.big}>{money(revenue - expenses, settings.currency)}</Text><Text style={styles.muted}>Net profit this period</Text><View style={styles.line}><View><Text style={styles.label}>Revenue</Text><MoneyText value={revenue} currency={settings.currency} /></View><View><Text style={styles.label}>Expenses</Text><MoneyText value={expenses} currency={settings.currency} /></View></View></AppCard><SectionHeader title="Working capital" /><View style={styles.heroRow}><MetricCard label="Accounts receivable" value={compactMoney(receivables, settings.currency)} detail="Open invoices" tone="yellow" /><MetricCard label="Accounts payable" value={compactMoney(8600, settings.currency)} detail="Due this week" tone="peach" /></View><AppCard style={styles.balanceCard}><Text style={styles.cardKicker}>BALANCE SHEET SNAPSHOT</Text>{[['Assets', 815000], ['Liabilities', 127000], ["Owner’s equity", 688000]].map(([label, value]) => <View key={label as string} style={styles.balanceRow}><Text style={styles.label}>{label as string}</Text><Text style={styles.balanceValue}>{money(value as number, settings.currency)}</Text></View>)}<Text style={styles.note}>Accounting detail is organized for future double-entry workflows.</Text></AppCard><AppCard tone="blue" style={styles.drill}><Text style={styles.drillTitle}>Go deeper when you’re ready</Text><Text style={styles.muted}>Review journal entries, accounts, and audit-ready detail without cluttering the owner view.</Text><Text onPress={() => router.push('/(tabs)/transactions')} style={styles.link}>Open transaction detail →</Text></AppCard></ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingTop: 58, paddingBottom: 50 }, heroRow: { flexDirection: 'row', gap: 10, marginVertical: 18 }, cardKicker: { color: colors.orangeDark, fontSize: 11, fontWeight: '900', letterSpacing: 1 }, big: { color: colors.ink, fontSize: 34, fontWeight: '900', marginTop: 10, fontVariant: ['tabular-nums'] }, muted: { color: colors.muted, marginTop: 5, lineHeight: 19 }, line: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 22, paddingTop: 16, borderTopWidth: 1, borderTopColor: colors.border }, label: { color: colors.muted, fontSize: 12, marginBottom: 6 }, balanceCard: { marginTop: 10 }, balanceRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: colors.border }, balanceValue: { color: colors.ink, fontWeight: '900', fontVariant: ['tabular-nums'] }, note: { color: colors.textMuted, fontSize: 11, marginTop: 16, lineHeight: 17 }, drill: { marginTop: 18 }, drillTitle: { color: colors.ink, fontSize: 17, fontWeight: '900' }, link: { color: colors.orangeDark, fontWeight: '900', marginTop: 14 } });
