import React from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { AppCard, ScreenHeader, SecurityBadge } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { colors, spacing } from '@/theme';
import { listNotifications, markNotificationRead, type AppNotification } from '@/services/notifications';

export default function NotificationsScreen() {
  const { user } = useAuth(); const [items, setItems] = React.useState<AppNotification[]>([]); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState<string | null>(null);
  const load = React.useCallback(async () => { if (!user) { setLoading(false); return; } setLoading(true); try { setItems(await listNotifications()); setError(null); } catch { setError('Notifications could not be loaded. Check your connection and try again.'); } finally { setLoading(false); } }, [user]);
  React.useEffect(() => { void load(); }, [load]);
  const read = async (item: AppNotification) => { if (!item.read_at) { try { await markNotificationRead(item.id); setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, read_at: new Date().toISOString() } : entry)); } catch { /* keep the notification visible if the network is unavailable */ } } };
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>Back</Text></Pressable><ScreenHeader eyebrow="WORKSPACE" title="Notifications" subtitle="Important activity from your finance workspace." /><SecurityBadge />{!user ? <AppCard style={styles.center}><Text style={styles.title}>Sign in to view notifications</Text><Pressable style={styles.button} onPress={() => router.push('/auth')}><Text style={styles.buttonText}>Sign in securely</Text></Pressable></AppCard> : loading ? <View style={styles.center}><ActivityIndicator color={colors.orange} /></View> : error ? <AppCard tone="peach" style={styles.center}><Text style={styles.error}>{error}</Text><Pressable onPress={() => void load()}><Text style={styles.retry}>Try again</Text></Pressable></AppCard> : items.length === 0 ? <AppCard tone="lavender" style={styles.center}><Text style={styles.emptyIcon}>✓</Text><Text style={styles.title}>You’re all caught up</Text><Text style={styles.body}>New invoice, review, and security alerts will appear here.</Text></AppCard> : items.map((item) => <Pressable key={item.id} onPress={() => void read(item)}><AppCard style={[styles.item, !item.read_at && styles.unread]}><View style={styles.itemTop}><Text style={styles.kind}>{item.kind.replaceAll('_', ' ').toUpperCase()}</Text>{!item.read_at ? <View style={styles.dot} /> : null}</View><Text style={styles.itemTitle}>{item.title}</Text><Text style={styles.itemBody}>{item.body}</Text><Text style={styles.date}>{new Date(item.created_at).toLocaleString()}</Text></AppCard></Pressable>)}</ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingTop: 54, paddingBottom: 110 }, back: { color: colors.orangeDark, fontWeight: '800', marginBottom: 24 }, center: { marginTop: 22, alignItems: 'center', paddingVertical: 30 }, title: { color: colors.ink, fontWeight: '900', fontSize: 18, textAlign: 'center' }, body: { color: colors.muted, lineHeight: 19, textAlign: 'center', marginTop: 8 }, emptyIcon: { color: colors.success, fontSize: 30, marginBottom: 8 }, item: { marginTop: 12 }, unread: { borderColor: colors.orange, borderWidth: 1.5 }, itemTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, kind: { color: colors.orangeDark, fontWeight: '900', fontSize: 10, letterSpacing: 1 }, dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.orange }, itemTitle: { color: colors.ink, fontSize: 16, fontWeight: '900', marginTop: 10 }, itemBody: { color: colors.muted, lineHeight: 19, marginTop: 5 }, date: { color: colors.textMuted, fontSize: 11, marginTop: 12 }, error: { color: colors.danger, textAlign: 'center', lineHeight: 19 }, retry: { color: colors.orangeDark, fontWeight: '900', marginTop: 14 }, button: { backgroundColor: colors.ink, borderRadius: 14, paddingHorizontal: 18, paddingVertical: 13, marginTop: 16 }, buttonText: { color: colors.surface, fontWeight: '900' } });
