import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { PrimaryButton } from '@/components/ui';
import { colors, spacing } from '@/theme';
import { useApp } from '@/context/AppContext';

const slides = [['Know where your money goes', 'A clear, human view of what came in, what went out, and what is safe to spend.', '◌'], ['Get paid on time', 'See who owes you, send kind reminders, and turn completed work into healthy cash flow.', '↗'], ['Grow with financial clarity', 'Spot your best clients and make confident decisions without accounting jargon.', '✦']];
export default function Onboarding() {
  const { settings } = useApp(); const [index, setIndex] = React.useState(0); const [business, setBusiness] = React.useState(settings.businessType || 'Agency'); const [currency, setCurrency] = React.useState(settings.currency || 'PKR'); const slide = slides[index];
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.top}><Text style={styles.brand}>ledgerflow</Text><Pressable onPress={() => router.back()}><Text style={styles.skip}>Skip</Text></Pressable></View><View style={styles.art}><Text style={styles.artText}>{slide[2]}</Text><View style={styles.orb} /></View><Text style={styles.title}>{slide[0]}</Text><Text style={styles.body}>{slide[1]}</Text><View style={styles.dots}>{slides.map((_, i) => <View key={i} style={[styles.dot, i === index && styles.dotActive]} />)}</View>{index < 2 ? <PrimaryButton label="Continue" onPress={() => setIndex(index + 1)} /> : <><Text style={styles.label}>What kind of business are you?</Text><View style={styles.options}>{['Agency','Freelancer','Consultant','Shop','Clinic','Contractor'].map((item) => <Pressable key={item} onPress={() => setBusiness(item)} style={[styles.option, business === item && styles.optionActive]}><Text style={[styles.optionText, business === item && styles.optionTextActive]}>{item}</Text></Pressable>)}</View><Text style={styles.label}>Your primary currency</Text><View style={styles.options}>{['PKR','USD','GBP','EUR'].map((item) => <Pressable key={item} onPress={() => setCurrency(item as 'PKR'|'USD'|'GBP'|'EUR')} style={[styles.option, currency === item && styles.optionActive]}><Text style={[styles.optionText, currency === item && styles.optionTextActive]}>{item}</Text></Pressable>)}</View><PrimaryButton label="Set up my workspace" onPress={() => router.back()} /></>}</ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingTop: 58, paddingBottom: 40 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, brand: { color: colors.ink, fontSize: 22, fontWeight: '900' }, skip: { color: colors.orangeDark, fontWeight: '800' }, art: { height: 240, backgroundColor: colors.lavender, borderRadius: 34, marginTop: 24, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, orb: { position: 'absolute', width: 160, height: 160, borderRadius: 90, backgroundColor: colors.orange, right: -30, bottom: -20, opacity: .88 }, artText: { color: colors.ink, fontSize: 82, fontWeight: '200', zIndex: 1 }, title: { color: colors.ink, fontSize: 31, lineHeight: 37, fontWeight: '900', marginTop: 28 }, body: { color: colors.muted, fontSize: 15, lineHeight: 23, marginTop: 12 }, dots: { flexDirection: 'row', gap: 6, marginVertical: 24 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.border }, dotActive: { width: 24, backgroundColor: colors.orange }, label: { color: colors.ink, fontWeight: '900', fontSize: 14, marginTop: 16, marginBottom: 10 }, options: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 4 }, option: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 11 }, optionActive: { backgroundColor: colors.ink, borderColor: colors.ink }, optionText: { color: colors.muted, fontWeight: '700' }, optionTextActive: { color: '#fff' } });
