import { createContext, PropsWithChildren, useContext, useEffect, useMemo, useState } from 'react';
import * as Linking from 'expo-linking';
import type { AuthenticatorAssuranceLevels, Factor, Session, User } from '@supabase/supabase-js';
import { hasSupabaseConfig, supabase } from '@/lib/supabase';
import type { MemberRole } from '@/lib/authorization';

type Membership = { organization_id: string; role: MemberRole; status: 'invited' | 'active' | 'disabled' };
type AuthContextValue = { ready: boolean; configured: boolean; user: User | null; session: Session | null; memberships: Membership[]; error: string | null; signIn: (email: string, password: string) => Promise<boolean>; signUp: (email: string, password: string, fullName: string) => Promise<boolean>; sendPasswordReset: (email: string) => Promise<boolean>; signOut: () => Promise<void>; requestAccountDeletion: (reason?: string) => Promise<boolean>; refreshMemberships: () => Promise<void>; getMfaStatus: () => Promise<{ currentLevel: AuthenticatorAssuranceLevels; nextLevel: AuthenticatorAssuranceLevels; factors: Factor[] }>; enrollMfa: (friendlyName: string) => Promise<{ factorId: string; qrCode: string } | null>; verifyMfa: (factorId: string, code: string) => Promise<boolean> };
const AuthContext = createContext<AuthContextValue | null>(null);
const GENERIC_AUTH_ERROR = 'We could not complete that request. Check your details and try again.';

export function AuthProvider({ children }: PropsWithChildren) {
  const [session, setSession] = useState<Session | null>(null); const [memberships, setMemberships] = useState<Membership[]>([]); const [ready, setReady] = useState(!hasSupabaseConfig); const [error, setError] = useState<string | null>(null);
  const refreshMemberships = async () => { if (!session?.user) return; const { data } = await supabase.from('organization_members').select('organization_id,role,status').eq('user_id', session.user.id); setMemberships((data ?? []) as Membership[]); };
  useEffect(() => { if (!hasSupabaseConfig) return; let active = true; const restoreDeepLink = async (url: string | null) => { if (!url) return; const parsed = new URL(url); const hash = new URLSearchParams(parsed.hash.replace(/^#/, '')); const query = parsed.searchParams; const accessToken = hash.get('access_token') ?? query.get('access_token'); const refreshToken = hash.get('refresh_token') ?? query.get('refresh_token'); const code = query.get('code'); if (accessToken && refreshToken) await supabase.auth.setSession({ access_token: accessToken, refresh_token: refreshToken }); else if (code) await supabase.auth.exchangeCodeForSession(code); }; supabase.auth.getSession().then(({ data }) => { if (active) { setSession(data.session); setReady(true); } }); Linking.getInitialURL().then(restoreDeepLink); const linkSubscription = Linking.addEventListener('url', ({ url }) => { restoreDeepLink(url); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, next) => { setSession(next); setReady(true); }); return () => { active = false; linkSubscription.remove(); listener.subscription.unsubscribe(); }; }, []);
  useEffect(() => { refreshMemberships(); }, [session?.user.id]);
  const clearError = () => setError(null);
  const signIn = async (email: string, password: string) => { clearError(); if (!hasSupabaseConfig) { setError('Supabase is not configured for this build.'); return false; } const { error: authError } = await supabase.auth.signInWithPassword({ email: email.trim().toLowerCase(), password }); if (authError) { setError(GENERIC_AUTH_ERROR); return false; } return true; };
  const signUp = async (email: string, password: string, fullName: string) => { clearError(); if (!hasSupabaseConfig) { setError('Supabase is not configured for this build.'); return false; } const { error: authError } = await supabase.auth.signUp({ email: email.trim().toLowerCase(), password, options: { data: { full_name: fullName.trim() } } }); if (authError) { setError(GENERIC_AUTH_ERROR); return false; } return true; };
  const sendPasswordReset = async (email: string) => { clearError(); if (!hasSupabaseConfig) { setError('Supabase is not configured for this build.'); return false; } await supabase.auth.resetPasswordForEmail(email.trim().toLowerCase(), { redirectTo: 'ledgerflow://auth/reset' }); return true; };
  const signOut = async () => { await supabase.auth.signOut(); setMemberships([]); };
  const requestAccountDeletion = async (reason?: string) => { clearError(); const { error: requestError } = await supabase.functions.invoke('request-account-deletion', { body: { reason: reason?.slice(0, 1000) } }); if (requestError) { setError('We could not submit the deletion request. Please try again.'); return false; } return true; };
  const getMfaStatus = async () => { const { data } = await supabase.auth.mfa.getAuthenticatorAssuranceLevel(); const factors = session?.user ? (await supabase.auth.mfa.listFactors()).data?.all ?? [] : []; return { currentLevel: data?.currentLevel ?? 'aal1', nextLevel: data?.nextLevel ?? 'aal1', factors }; };
  const enrollMfa = async (friendlyName: string) => { const { data, error: factorError } = await supabase.auth.mfa.enroll({ factorType: 'totp', friendlyName: friendlyName.slice(0, 80) }); if (factorError || !data) return null; return { factorId: data.id, qrCode: data.totp.qr_code }; };
  const verifyMfa = async (factorId: string, code: string) => { const { data: challenge, error: challengeError } = await supabase.auth.mfa.challenge({ factorId }); if (challengeError || !challenge) return false; const { error: verifyError } = await supabase.auth.mfa.verify({ factorId, challengeId: challenge.id, code }); return !verifyError; };
  const value = useMemo(() => ({ ready, configured: hasSupabaseConfig, user: session?.user ?? null, session, memberships, error, signIn, signUp, sendPasswordReset, signOut, requestAccountDeletion, refreshMemberships, getMfaStatus, enrollMfa, verifyMfa }), [ready, session, memberships, error]);
  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}
export function useAuth() { const ctx = useContext(AuthContext); if (!ctx) throw new Error('useAuth must be used inside AuthProvider'); return ctx; }
