import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { AppCard, SectionHeader, StatusPill } from '@/components/ui';
import { useApp } from '@/context/AppContext';
import { colors, money, spacing } from '@/theme';
import type { Transaction } from '@/types';

export default function TransactionsScreen() {
  const { transactions, settings } = useApp();
  const [filter, setFilter] = React.useState('All');
  const [query, setQuery] = React.useState('');
  const filters = ['All', 'Income', 'Expenses', 'Needs review'];
  const visible = transactions.filter((tx) => (filter === 'All' || (filter === 'Income' && tx.type === 'income') || (filter === 'Expenses' && tx.type === 'expense') || (filter === 'Needs review' && tx.status === 'Needs review')) && `${tx.merchant} ${tx.category}`.toLowerCase().includes(query.toLowerCase()));
  return <View style={styles.screen}><FlatList data={visible} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><Text style={styles.eyebrow}>MONEY MOVEMENT</Text><View style={styles.headerRow}><View><Text style={styles.title}>Transactions</Text><Text style={styles.sub}>Every inflow and outflow, in one calm view.</Text></View><Pressable style={styles.add} onPress={() => router.push('/add?mode=expense' as never)}><Text style={styles.addText}>＋</Text></Pressable></View><TextInput value={query} onChangeText={setQuery} placeholder="Search merchant or category" placeholderTextColor={colors.muted} style={styles.search} /><View style={styles.filters}>{filters.map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, filter === item && styles.filterActive]}><Text style={[styles.filterText, filter === item && styles.filterTextActive]}>{item}</Text></Pressable>)}</View><SectionHeader title={`${visible.length} transactions`} action="This month" /></>} renderItem={({ item }) => <TransactionRow item={item} currency={settings.currency} />} ListEmptyComponent={<AppCard tone="lavender"><Text style={styles.emptyTitle}>Nothing matches that filter</Text><Text style={styles.emptyBody}>Try another search or add a new transaction.</Text></AppCard>} /> </View>;
}
function TransactionRow({ item, currency }: { item: Transaction; currency: 'PKR' | 'USD' | 'GBP' | 'EUR' }) { return <AppCard style={styles.row}><View style={[styles.txIcon, { backgroundColor: item.type === 'income' ? colors.mint : colors.peach }]}><Text style={styles.txIconText}>{item.type === 'income' ? '↗' : '↘'}</Text></View><View style={styles.rowMain}><Text style={styles.merchant}>{item.merchant}</Text><Text style={styles.meta}>{item.category} · {item.date.slice(5).replace('-', '/')}</Text><StatusPill label={item.status} kind={item.status === 'Completed' ? 'positive' : item.status === 'Needs review' ? 'warning' : 'neutral'} /></View><Text style={[styles.amount, { color: item.type === 'income' ? colors.success : colors.ink }]}>{item.type === 'income' ? '+' : '−'}{money(item.amount, currency)}</Text></AppCard>; }
import React from 'react';
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingTop: 58, paddingBottom: 120 }, eyebrow: { color: colors.muted, fontWeight: '800', fontSize: 10, letterSpacing: 1.2 }, headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8, marginBottom: 20 }, title: { color: colors.ink, fontSize: 30, fontWeight: '900' }, sub: { color: colors.muted, marginTop: 5, maxWidth: 250 }, add: { width: 48, height: 48, borderRadius: 17, backgroundColor: colors.orange, alignItems: 'center', justifyContent: 'center' }, addText: { color: '#fff', fontSize: 25 }, search: { height: 52, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 16, paddingHorizontal: 16, color: colors.ink, marginBottom: 14 }, filters: { flexDirection: 'row', gap: 7, marginBottom: 26 }, filter: { paddingVertical: 9, paddingHorizontal: 12, borderRadius: 20, backgroundColor: colors.surface }, filterActive: { backgroundColor: colors.ink }, filterText: { color: colors.muted, fontWeight: '700', fontSize: 12 }, filterTextActive: { color: '#fff' }, row: { flexDirection: 'row', alignItems: 'center', padding: 14, marginBottom: 10 }, txIcon: { width: 42, height: 42, borderRadius: 15, alignItems: 'center', justifyContent: 'center', marginRight: 12 }, txIconText: { color: colors.ink, fontSize: 20 }, rowMain: { flex: 1 }, merchant: { color: colors.ink, fontWeight: '900', fontSize: 14 }, meta: { color: colors.muted, fontSize: 11, marginVertical: 4 }, amount: { fontWeight: '900', fontSize: 13, alignSelf: 'flex-start' }, emptyTitle: { fontSize: 18, color: colors.ink, fontWeight: '900' }, emptyBody: { color: colors.muted, marginTop: 6 }, });
