import React from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { AppCard, PrimaryButton, SectionHeader, StatusPill } from '@/components/ui';
import { useApp } from '@/context/AppContext';
import { colors, compactMoney, money, spacing } from '@/theme';
import type { Invoice } from '@/types';

export default function InvoicesScreen() {
  const { invoices, settings, markInvoicePaid } = useApp();
  const [filter, setFilter] = React.useState('All');
  const collect = invoices.reduce((sum, item) => sum + item.balanceDue, 0);
  const visible = invoices.filter((i) => filter === 'All' || i.status === filter.toLowerCase());
  return <View style={styles.screen}><FlatList data={visible} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.headerRow}><View><Text style={styles.eyebrow}>GET PAID ON TIME</Text><Text style={styles.title}>Invoices</Text><Text style={styles.sub}>Simple, friendly collections for your clients.</Text></View><Pressable onPress={() => router.push('/add?mode=invoice' as never)} style={styles.add}><Text style={styles.addText}>＋</Text></Pressable></View><AppCard tone="peach" style={styles.summary}><Text style={styles.summaryLabel}>AMOUNT TO COLLECT</Text><Text style={styles.summaryAmount}>{money(collect, settings.currency)}</Text><Text style={styles.summaryNote}>Across {invoices.filter((i) => i.balanceDue > 0).length} open invoices · one kind nudge at a time.</Text></AppCard><View style={styles.filters}>{['All','Draft','Sent','Paid','Overdue'].map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, filter === item && styles.filterActive]}><Text style={[styles.filterText, filter === item && styles.filterTextActive]}>{item}</Text></Pressable>)}</View><SectionHeader title="Your invoices" action="September" /></>} renderItem={({ item }) => <InvoiceRow item={item} currency={settings.currency} onPaid={() => markInvoicePaid(item.id)} />} ListEmptyComponent={<AppCard tone="lavender"><Text style={styles.emptyTitle}>No invoices here yet</Text><Text style={styles.emptyBody}>Create one and give your cash flow a little momentum.</Text></AppCard>} /></View>;
}
function InvoiceRow({ item, currency, onPaid }: { item: Invoice; currency: 'PKR'|'USD'|'GBP'|'EUR'; onPaid: () => void }) { const kind = item.status === 'paid' ? 'positive' : item.status === 'overdue' ? 'danger' : item.status === 'sent' || item.status === 'viewed' ? 'warning' : 'neutral'; return <AppCard style={styles.invoice}><View style={styles.invoiceTop}><View><Text style={styles.invoiceId}>{item.id}</Text><Text style={styles.client}>{item.client}</Text></View><StatusPill label={item.status} kind={kind} /></View><Text style={styles.project}>{item.project} · Due {item.dueDate.slice(5).replace('-', '/')}</Text><View style={styles.invoiceBottom}><View><Text style={styles.invoiceAmount}>{money(item.amount, currency)}</Text><Text style={styles.balance}>{item.balanceDue ? `${compactMoney(item.balanceDue, currency)} to collect` : 'Paid in full'}</Text></View>{item.status !== 'paid' ? <PrimaryButton label="Mark paid" onPress={onPaid} secondary /> : <Text style={styles.paid}>✓ Collected</Text>}</View></AppCard>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingTop: 58, paddingBottom: 120 }, headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }, eyebrow: { color: colors.muted, fontWeight: '800', fontSize: 10, letterSpacing: 1.2 }, title: { color: colors.ink, fontSize: 30, fontWeight: '900', marginTop: 8 }, sub: { color: colors.muted, marginTop: 5, maxWidth: 250 }, add: { width: 48, height: 48, borderRadius: 17, backgroundColor: colors.orange, alignItems: 'center', justifyContent: 'center' }, addText: { color: '#fff', fontSize: 25 }, summary: { marginBottom: 24 }, summaryLabel: { color: colors.orangeDark, fontWeight: '900', fontSize: 11, letterSpacing: 1 }, summaryAmount: { color: colors.ink, fontSize: 32, fontWeight: '900', marginTop: 8 }, summaryNote: { color: colors.muted, marginTop: 8, lineHeight: 18 }, filters: { flexDirection: 'row', gap: 7, marginBottom: 26 }, filter: { paddingVertical: 9, paddingHorizontal: 12, borderRadius: 20, backgroundColor: colors.surface }, filterActive: { backgroundColor: colors.ink }, filterText: { color: colors.muted, fontWeight: '700', fontSize: 12 }, filterTextActive: { color: '#fff' }, invoice: { marginBottom: 12 }, invoiceTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' }, invoiceId: { color: colors.muted, fontSize: 11, fontWeight: '800' }, client: { color: colors.ink, fontWeight: '900', fontSize: 17, marginTop: 4 }, project: { color: colors.muted, fontSize: 12, marginTop: 12 }, invoiceBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginTop: 18 }, invoiceAmount: { color: colors.ink, fontWeight: '900', fontSize: 18 }, balance: { color: colors.muted, fontSize: 11, marginTop: 4 }, paid: { color: colors.success, fontWeight: '900', paddingBottom: 8 }, emptyTitle: { fontSize: 18, color: colors.ink, fontWeight: '900' }, emptyBody: { color: colors.muted, marginTop: 6 }, });
